# Generated by Django 4.2.5 on 2023-10-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeStartPeriod', models.DateTimeField()),
                ('datetimeFinalPeriod', models.DateTimeField()),
                ('datetimeFinalApplication', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='academicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAcademicProgram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='educationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationLevel', models.CharField(max_length=100)),
                ('descriptionEducationLevel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='guestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGroup', models.CharField(max_length=700)),
                ('groupDescription', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='processStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProcessStage', models.CharField(max_length=60)),
                ('descriptionProcessStage', models.CharField(max_length=60)),
                ('backProcessStage', models.CharField(max_length=60)),
                ('nextProcessStage', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeRole', models.CharField(max_length=150)),
                ('descriptionRole', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='statusAcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusAcademicProgram', models.CharField(max_length=100)),
                ('descriptionStatusAcademicProgram', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='statusApplicartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusApplicartion', models.CharField(max_length=60)),
                ('descriptionStatusApplicartion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='statusFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusFaculty', models.CharField(max_length=100)),
                ('descriptionStatusFacult', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='statusSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusSubject', models.CharField(max_length=100)),
                ('descriptionStatusSubject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='statusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusUser', models.CharField(max_length=100)),
                ('descriptionStatusUser', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='studyModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyModality', models.CharField(max_length=100)),
                ('descriptionModality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSubject', models.CharField(max_length=100)),
                ('academicProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.academicprogram')),
                ('statusSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statussubject')),
            ],
        ),
        migrations.CreateModel(
            name='typeIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeIdentification', models.CharField(max_length=100)),
                ('descriptionTypeIdentification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=100)),
                ('lastNameUser', models.CharField(max_length=100)),
                ('PEGE_ID', models.IntegerField()),
                ('identificationNumber', models.IntegerField()),
                ('statusUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statususer')),
                ('typeIdentification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.typeidentification')),
            ],
        ),
        migrations.CreateModel(
            name='userFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFunction', models.CharField(max_length=50)),
                ('descriptionUser', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('finaleDate', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='requestInvitaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeRequestInvitaction', models.DateTimeField()),
                ('guestGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.guestgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
                ('userFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.userfunction')),
            ],
        ),
        migrations.CreateModel(
            name='processStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeUpdateProcess', models.DateTimeField()),
                ('processStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.processstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='notificationRequestInvitaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationDetail', models.CharField(max_length=700)),
                ('meansNotification', models.CharField(max_length=60)),
                ('datetimeNotification', models.DateTimeField()),
                ('requestInvitaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.requestinvitaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFaculty', models.CharField(max_length=100)),
                ('statusFaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statusfaculty')),
            ],
        ),
        migrations.CreateModel(
            name='applicartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeStartapplicartion', models.DateTimeField()),
                ('datetimeFinalapplicartion', models.DateTimeField()),
                ('routePracticeProject', models.CharField(max_length=500)),
                ('routeWorkGuide', models.CharField(max_length=500)),
                ('typePractice', models.CharField(max_length=50)),
                ('routeAcceptancedocument', models.CharField(max_length=500)),
                ('routeContigencyPlan', models.CharField(max_length=500)),
                ('academicPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.academicperiod')),
                ('processStageHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.processstagehistory')),
                ('statusApplicartion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statusapplicartion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='educationLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.educationlevel'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.faculty'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='statusAcademicProgram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statusacademicprogram'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='studyModality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.studymodality'),
        ),
    ]
