# Generated by Django 4.2.5 on 2023-10-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeStartPeriod', models.DateTimeField()),
                ('datetimeFinalPeriod', models.DateTimeField()),
                ('datetimeFinalApplication', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='applicartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeStartapplicartion', models.DateTimeField()),
                ('datetimeFinalapplicartion', models.DateTimeField()),
                ('routePracticeProject', models.FileField(upload_to='files/projects/')),
                ('routeWorkGuide', models.FileField(upload_to='files/workGuide/')),
                ('typePractice', models.CharField(max_length=50)),
                ('routeAcceptancedocument', models.FileField(upload_to='files/acceptanceDocument/')),
                ('routeContigencyPlan', models.FileField(upload_to='files/contingencyPlan/')),
                ('academicPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.academicperiod')),
            ],
        ),
        migrations.CreateModel(
            name='CRUDPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_CRUD', 'Can perform CRUD operations')],
            },
        ),
        migrations.CreateModel(
            name='educationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationLevel', models.CharField(max_length=100)),
                ('descriptionEducationLevel', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='guestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGroup', models.CharField(max_length=700)),
                ('groupDescription', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='processStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProcessStage', models.CharField(max_length=60)),
                ('descriptionProcessStage', models.CharField(max_length=60)),
                ('backProcessStage', models.CharField(max_length=60)),
                ('nextProcessStage', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeRole', models.CharField(max_length=150)),
                ('descriptionRole', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='statusApplicartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusApplicartion', models.CharField(max_length=60)),
                ('descriptionStatusApplicartion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='statusSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusSubject', models.CharField(max_length=100)),
                ('descriptionStatusSubject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='statusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusunit', models.CharField(max_length=100)),
                ('descriptionStatusunit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='statusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatusUser', models.CharField(max_length=100)),
                ('descriptionStatusUser', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='studyModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyModality', models.CharField(max_length=100)),
                ('descriptionModality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSubject', models.CharField(max_length=100)),
                ('statusSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statussubject')),
            ],
        ),
        migrations.CreateModel(
            name='typeIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeIdentification', models.CharField(max_length=100)),
                ('descriptionTypeIdentification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='typeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameType', models.CharField(max_length=70)),
                ('descriptionTypeUnit', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=100)),
                ('lastNameUser', models.CharField(max_length=100)),
                ('PEGE_ID', models.IntegerField()),
                ('identificationNumber', models.IntegerField()),
                ('statusUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statususer')),
                ('typeIdentification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.typeidentification')),
            ],
        ),
        migrations.CreateModel(
            name='userFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFunction', models.CharField(max_length=50)),
                ('descriptionUser', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('finaleDate', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameunit', models.CharField(max_length=100)),
                ('descriptionUnit', models.CharField(max_length=100)),
                ('educationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.educationlevel')),
                ('statusUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statusunit')),
                ('studyModality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.studymodality')),
                ('typeUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.typeunit')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.unit'),
        ),
        migrations.CreateModel(
            name='requestInvitaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeRequestInvitaction', models.DateTimeField()),
                ('guestGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.guestgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
                ('userFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.userfunction')),
            ],
        ),
        migrations.CreateModel(
            name='processStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeUpdateProcess', models.DateTimeField()),
                ('justification', models.CharField(max_length=500)),
                ('processStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.processstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='practiceAssistants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeConfirmation', models.DateTimeField()),
                ('nameEPS', models.CharField(max_length=50)),
                ('certificateEPS', models.FileField(upload_to='files/certificatesEPS/')),
                ('applicartion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.applicartion')),
                ('requestInvitaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.requestinvitaction')),
            ],
        ),
        migrations.CreateModel(
            name='notificationRequestInvitaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationDetail', models.CharField(max_length=700)),
                ('meansNotification', models.CharField(max_length=60)),
                ('datetimeNotification', models.DateTimeField()),
                ('requestInvitaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.requestinvitaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.CreateModel(
            name='headUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeCreate', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
            ],
        ),
        migrations.AddField(
            model_name='applicartion',
            name='processStageHistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.processstagehistory'),
        ),
        migrations.AddField(
            model_name='applicartion',
            name='statusApplicartion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.statusapplicartion'),
        ),
        migrations.AddField(
            model_name='applicartion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user'),
        ),
    ]
