# Generated by Django 4.2.5 on 2023-10-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicasAcademicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ancestor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='predecessor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='typeunit',
            name='descriptionTypeUnit',
            field=models.CharField(max_length=500),
        ),
    ]
