# Generated by Django 4.2.5 on 2023-10-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicasAcademicas', '0002_unit_ancestor_unit_predecessor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='predecessor',
        ),
    ]
