# Generated by Django 4.2.5 on 2023-10-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicasAcademicas', '0004_alter_unit_descriptionunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='ancestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.unit'),
        ),
    ]
