# Generated by Django 4.2.5 on 2023-10-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicasAcademicas', '0006_alter_processstage_descriptionprocessstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameWorkerRole', models.CharField(max_length=50)),
                ('DescriptionWorkerRole', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='workerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeCreate', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.user')),
                ('workerRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.workerrole')),
            ],
        ),
        migrations.RenameModel(
            old_name='role',
            new_name='roleAcademic',
        ),
        migrations.RenameModel(
            old_name='userRole',
            new_name='userRoleAcademic',
        ),
        migrations.RenameField(
            model_name='roleacademic',
            old_name='descriptionRole',
            new_name='descriptionRoleAcademic',
        ),
        migrations.RenameField(
            model_name='roleacademic',
            old_name='typeRole',
            new_name='typeRoleAcademic',
        ),
        migrations.RenameField(
            model_name='userroleacademic',
            old_name='role',
            new_name='roleAcademic',
        ),
        migrations.DeleteModel(
            name='headUnit',
        ),
    ]
