# Generated by Django 4.2.5 on 2023-10-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicasAcademicas', '0007_workerrole_workerunit_rename_role_roleacademic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeAcademicPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAcademicPractice', models.CharField(max_length=50)),
                ('DescriptionAcademicPractice', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='applicartion',
            name='routeAcceptancedocument',
            field=models.FileField(upload_to='acceptanceDocument/'),
        ),
        migrations.AlterField(
            model_name='applicartion',
            name='routeContigencyPlan',
            field=models.FileField(upload_to='contingencyPlan/'),
        ),
        migrations.AlterField(
            model_name='applicartion',
            name='routePracticeProject',
            field=models.FileField(db_index=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='applicartion',
            name='routeWorkGuide',
            field=models.FileField(db_index=True, upload_to='workGuide/'),
        ),
        migrations.AddField(
            model_name='applicartion',
            name='typeAcademicPractice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practicasAcademicas.typeacademicpractice'),
        ),
    ]
